import Airtable from "airtable";
import Head from "next/head";
import Link from "next/link";
import { useState, useEffect } from "react";

import getCommunities from "/lib/getCommunities";
import Page from "/components/Page";
import Map from "/components/Map";
import styles from "/styles/App.module.css";

export async function getStaticPaths() {
  const communities = await getCommunities();

  return {
    paths: communities.map((community) => {
      return {
        params: community,
      };
    }),
    fallback: "blocking",
  };
}

export async function getStaticProps({ params }) {
  const airtable = new Airtable({
    apiKey: process.env.AIRTABLE_API_KEY,
  });

  const records = await airtable
    .base("appi2zZaHEKWDWKt6")("Communities")
    .select({
      fields: [
        "name",
        "lat",
        "lng",
        "slug",
        "rank",
        "risk",
        "country",
        "population",
      ],
    })
    .all();

  const communities = records.map((product) => {
    return {
      name: product.get("name"),
      lat: product.get("lat"),
      lng: product.get("lng"),
      slug: product.get("slug"),
      rank: product.get("rank"),
      risk: product.get("risk"),
      country: product.get("country"),
      population: product.get("population"),
    };
  });

  const community = communities.find(
    (community) => community.slug === params.slug
  );

  return {
    props: {
      community,
      communities,
    },
  };
}

export default function Detail({ community, communities }) {
  return (
    <Page title={community.name} slug={community.slug}>
      <Head>
        <title>{community.name} Overview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.app}>
        <div className={styles.content}>
          <h3>Hazard</h3>
          <p className="large">
            {community.name} will see increased hazards in the future—in
            addition to risk that it will also experience. Did we mention hazard
            and risk are different?
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
            venenatis ligula aliquam magna elementum, in dapibus nisl pulvinar.
            In venenatis rutrum nisl, at rhoncus risus varius sit amet. Ut ut
            eros eros. Vivamus tincidunt quam urna, ut malesuada eros viverra
            sit amet. Nam est urna, ultricies id mauris sit amet, sodales
            fringilla ante. Ut nunc nulla, convallis eu nisl in, pulvinar cursus
            augue. Nullam dictum, metus ac suscipit aliquet, mi erat commodo
            velit, non interdum eros magna vel ligula.
          </p>
          <h3>Similar communities</h3>
          <ul>
            {communities.map((community) => (
              <li>
                <a href={`/community/${community.slug}/hazard`}>
                  {community.name}
                </a>
              </li>
            ))}
          </ul>
        </div>
        <div className={styles.map}>
          <Map lat={community.lat} lng={community.lng} />
        </div>
      </div>
    </Page>
  );
}
