import Head from "next/head";
import { useState, useEffect } from "react";

import Similar from "/components/Similar";
import MapLayout from "/components/MapLayout";

import getCommunities from "/lib/getCommunities";
import matchCommunity from "/lib/matchCommunity";

import styles from "/styles/App.module.css";

export async function getStaticPaths() {
  const communities = await getCommunities();

  return {
    paths: communities.map((community) => {
      return {
        params: community,
      };
    }),
    fallback: "blocking",
  };
}

export async function getStaticProps({ params }) {
  const communities = await getCommunities();
  const community = matchCommunity(params.slug, communities);

  return {
    props: {
      community,
      communities,
      color: "blue",
    },
  };
}

export default function Overview({ community, communities }) {
  return (
    <div>
      <Head>
        <title>{community.name} Overview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className={styles.content}>
          <h3>Overview</h3>
          <p className="large">
            {community.name} has a hazard risk of {community.risk} of 3—in the
            top {community.rank}% of communities in {community.country}.
          </p>
          <p>
            {community.name} is a community in {community.country} with a
            population of {community.population.toLocaleString()}. Like many of
            its neighbors, it will face an increase in hazard risk over the
            coming century. Climate mitigation efforts, such as science, will be
            able to help the community plan for and adapt to its future. In real
            time.
          </p>
          <h3>Similar communities</h3>
          <Similar community={community} communities={communities} />
        </div>
      </div>
    </div>
  );
}

Overview.PageLayout = MapLayout;
